version: '3.7'


networks:
  monitoring:
    external: true


services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - spring-postgres

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - spring-postgres
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana


volumes:
  prometheus-data:
  grafana-storage:
