# Dockerfile for PostgreSQL

FROM postgres:latest

# Environment variabless
ENV POSTGRES_DB=mydb
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# This is the file that is to Expose PostgreSQL default port
EXPOSE 5432
