# Dockerfile for PostgreSQL

FROM postgres:latest

# Environment variablesss
ENV POSTGRES_DB=mydb
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# This is the  Expose PostgreSQL default port
EXPOSE 5432
