# Dockerfile for PostgreSQL

FROM postgres:latest

# Environment variables
ENV POSTGRES_DB=mydb
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Expose PostgreSQL default ports
EXPOSE 5432
