version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${SPRINGBOOT_IMAGE_NAME:-springboot-app}:${SPRINGBOOT_IMAGE_TAG:-latest}
    container_name: springboot-app
    ports:
      - "8081:8081"
    networks:
      - spring-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

networks:
  spring-postgres:
    name: spring-postgres
